### PR TITLE
Added approach and naming conventions, Fixes #5

### LINKED ISSUE #5: Modify Readme
Add approach and naming conventions to readme

### PR DESCRIPTION
**Pull request by Madasanya**

### CODE REVIEW

**Review by VladDrgm — CHANGES_REQUESTED** [review]
Please change the typos.

**Review by VladDrgm — DISMISSED** [review]
Testing rejection.

**Review by VladDrgm — APPROVED** [review]
Approved.
Readme file correctly updated.

**Review by mr-bammby — COMMENTED** [review]
It seems good.

**Review by dejanzivanov — COMMENTED** [review]
Typos Fixed. Seems good.

**Pull request merged**
